# Generated by Django 4.2.1 on 2023-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('localidade', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('foi_a_igreja', models.BooleanField()),
            ],
        ),
    ]
